/**
 * lib/agentsmd.js - builds each thread's AGENTS.md.
 *
 * opencode automatically reads AGENTS.md from its working directory, so this
 * file is how a thread's charter, the harness conventions, and the global
 * go-to knowledge reach the engine on every single run - no prompt stuffing.
 *
 * Regenerated when a thread is created and via POST /api/thread/:name/sync
 * (the "Sync contract" button). Edit charter.md, then sync; never hand-edit
 * AGENTS.md (it gets overwritten and says so at the top).
 */
"use strict";
const fs = require("fs");
const path = require("path");

function safeRead(p) {
  try { return fs.readFileSync(p, "utf8").trim(); } catch (_) { return ""; }
}

/**
 * @param {string} root       Spindle root directory
 * @param {string} threadName folder name under threads/
 * @returns {string} AGENTS.md content
 */
function build(root, threadName) {
  const tdir = path.join(root, "threads", threadName);
  const charter = safeRead(path.join(tdir, "charter.md")) ||
    "(charter.md is empty - fill it in and press Sync contract)";

  return `<!-- GENERATED by Spindle from charter.md + harness rules. Do not edit directly:
     edit charter.md and press "Sync contract" in the UI (or POST /api/thread/${threadName}/sync). -->

# Thread: ${threadName}

You are the resident agent of this thread inside Spindle, ${""}a personal work
harness. This folder is your workspace and your memory. Everything below is
standing instruction for every session in this thread.

## Charter (what this thread is for)

${charter}

## Where things live (all paths relative to this folder)

- \`memory.md\` - your durable memory for this thread. Read it at the start of
  every session.
- \`skills/\` - your learned procedures for this thread's recurring work.
- \`inbox/\` - updates dropped here by the Scout (collector) or by the user.
  Unprocessed items sit at the top level; after you have incorporated an item,
  move it to \`inbox/read/\`.
- \`artifacts/\` - every file you produce for the user (reports, HTML, decks,
  data) goes here, nowhere else. The Spindle UI previews this folder.
- \`sessions/log.md\` - the conversation record. Spindle appends to it; you may
  read it to recall earlier turns.
- \`../../global/routing.md\` - the go-to map: where to look things up
  (SharePoint sites, Teams bots, systems of record). Consult it BEFORE asking
  the user where information lives.
- \`../../global/acronyms.md\` - org acronyms and shorthand.
- \`../../global/memory.md\` - durable facts about the user and their world.
- \`../../global/skills/\` - skills shared across all threads.

## Operating rules

1. **Start of session:** read \`memory.md\`, glance at unprocessed \`inbox/\`
   items, and use them as context without being asked.
2. **End of any substantial task:** update \`memory.md\` with durable facts and
   decisions (distilled - one line per fact). Never paste raw emails or Teams
   messages into memory; summarize.
3. **Learning loop (non-negotiable):** if a task took more than one attempt,
   or you discovered a procedure you would otherwise re-derive next time,
   write or update a skill in \`skills/\` before finishing: one markdown file,
   named for the task, starting with WHEN to use it, then the exact steps that
   worked, then pitfalls. If a matching skill exists, improve it instead of
   creating a duplicate.
4. **Artifacts:** anything the user will look at or share goes in
   \`artifacts/\` with a dated, descriptive filename. Prefer self-contained
   HTML for reports.
5. **Cross-thread help:** you may READ other threads under \`../\` for context
   (their charter.md, memory.md, artifacts). Do not write into another
   thread except by dropping a note into its \`inbox/\`.
6. **Subagents:** for parallelizable work (multi-source research, bulk
   processing), fan out with your subagent/task tooling; keep each scope
   narrow, and reconcile results with a verification pass before presenting.
   Log what you delegated and what came back in your reply so the user can
   audit it.
7. **Data hygiene:** distill, don't hoard. Summaries in memory, raw material
   stays in the systems of record. This harness must stay consistent with a
   governed-AI story: scoped access, auditable actions, no sensitive dumps.
8. **When unsure where information lives**, check \`../../global/routing.md\`
   first, then say what you checked.
`;
}

module.exports = { build };
