#!/usr/bin/env python3
"""Regenerate ui/themes.js from opencode's TUI theme assets.

Usage:
  1. Get the theme JSONs (in the opencode repo: packages/tui/src/theme/assets/)
  2. python scripts/convert-opencode-themes.py <path-to-assets-dir>

Reads every *.json theme, resolves its "defs" color names, keeps the 15
semantic tokens Spindle maps to CSS variables, and rewrites ui/themes.js
(keeping the built-in "spindle" theme first). Themes missing background/text/
primary in either variant are skipped.
"""
import json, os, sys, glob

KEEP = ["primary","secondary","accent","error","warning","success","info",
        "text","textMuted","background","backgroundPanel","backgroundElement",
        "border","borderActive","borderSubtle"]

SPINDLE = {
  "dark": {"primary":"#A9BCF0","secondary":"#C9A9E8","accent":"#E8B44C","error":"#E07B6A",
           "warning":"#E8B44C","success":"#7FBE9C","info":"#A9BCF0","text":"#E5EAF7",
           "textMuted":"#9FB0DC","background":"#131938","backgroundPanel":"#1B2148",
           "backgroundElement":"#232A55","border":"#4A5387","borderActive":"#6B76AD",
           "borderSubtle":"#333B6B"},
  "light": {"primary":"#1E2761","secondary":"#6E4B8E","accent":"#C98F1F","error":"#8C3A2E",
            "warning":"#C98F1F","success":"#3E7C59","info":"#3E6C93","text":"#232838",
            "textMuted":"#5A6478","background":"#F6F7FA","backgroundPanel":"#FFFFFF",
            "backgroundElement":"#EEF1F8","border":"#C6CFE3","borderActive":"#9AA7C8",
            "borderSubtle":"#DDE3F0"},
}

def resolve(val, defs, mode):
    if isinstance(val, dict):
        val = val.get(mode, val.get("dark"))
    if isinstance(val, str):
        return defs.get(val, val)
    return None

def main(assets_dir):
    themes = {"spindle": SPINDLE}
    for f in sorted(glob.glob(os.path.join(assets_dir, "*.json"))):
        name = os.path.basename(f)[:-5]
        try:
            d = json.load(open(f))
        except Exception as e:
            print("skip", name, e); continue
        defs, th, out, ok = d.get("defs", {}), d.get("theme", {}), {}, True
        for mode in ("dark","light"):
            toks = {}
            for k in KEEP:
                v = resolve(th.get(k), defs, mode)
                toks[k] = v if (isinstance(v,str) and v.startswith("#")) else None
            if not (toks["background"] and toks["text"] and toks["primary"]): ok = False
            out[mode] = toks
        if ok: themes[name] = out
        else: print("skip (incomplete):", name)
    dest = os.path.join(os.path.dirname(__file__), "..", "ui", "themes.js")
    with open(dest, "w") as fh:
        fh.write("/* GENERATED by scripts/convert-opencode-themes.py - do not hand-edit.\n")
        fh.write("   Source: opencode packages/tui/src/theme/assets/*.json */\n")
        fh.write("window.SPINDLE_THEMES = ")
        json.dump(themes, fh, indent=1)
        fh.write(";\n")
    print("wrote", dest, "with", len(themes), "themes")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
